### ISSUE TITLE
Do not insert metric tags every time metrics are reported

### ISSUE THREAD

**Issue by jsanda** [hawkular/hawkular-dropwizard-reporter#12]
Assuming metric tags do not change regularly, which I think is pretty typical, you do not have to re-insert metric tags each time when reporting metrics. Instead metric tags can be inserted once in the constructor of HawkularReporter using either 

```POST /hawkular/metrics/metrics/```

or

```POST /hawkular/metrics/counters```
```POST /hawkular/metrics/gauges```

You can use the same request body that is currently being used for adding tags.

**Comment by jotak** [comment]
I can't see how we can deal with tags in ctor since we don't know the metric names in advance. We know them only when there's incoming data. However IIRC, I did an evicting cache mechanism so that tags are not pushed at each report.

**Comment by jsanda** [comment]
Can you call MetricRegistry.getCounters and MetricRegistry.getGauges in the constructor? And to handle metrics that are added later, after initialization use a MetricRegistryListener.

**Comment by jotak** [comment]
Still, metrics could be created after the constructor is called... But I've just found MetricRegistry.addListener so we should probably sort it out.
