### ISSUE TITLE
Add support for dynamically generating global tags

### ISSUE THREAD

**Issue by jsanda** [hawkular/hawkular-dropwizard-reporter#19]
I am thinking specifically about the metrics we will collect from Cassandra. I am not yet 100% certain I need this, but I want to go ahead and discuss it. http://cassandra.apache.org/doc/latest/operating/metrics.html#metric-types is the full list of available metrics in Cassandra. There are two tags I want to add for each metric. The first I am calling `component` and its value is `org.apache.cassandra`. This allows me to easily find all Cassandra metrics. I already define this in my report-config file, e.g., 

```yaml
    globalTags:
      component: 'org.apache.cassandra'
```

For the second tag I want, consider the [commit log metrics](http://cassandra.apache.org/doc/latest/operating/metrics.html#commitlog-metrics) as an example. I want another tag whose value is `CommitLog`.

I need to prototype including Cassandra metrics in the new `/hawkular/metrics/admin/status` endpoint so that I have a better idea of what exactly we will need in hawkular-metrics. I will report back once I have done that.

**Comment by jotak** [comment]
So if I understand, for the second example, like CommitLog, it could either be done via listing extensively all metrics tagging in the yaml under the "perMetricsTags" node ; or, via implementing this enhancement: #7 (per-metric tagging with regexp). You would have something like that:

```yaml
    perMetricTags:
      "org\.apache\.cassandra\.CommitLog\..*":
        domain: 'CommitLog'
```
?

(though I'm not sure if I can put such a regexp as yaml key)

**Comment by jsanda** [comment]
Yeah, I think that is right. I am not 100% certain I need this though. I am going to do some prototyping today in hawkular-metrics, and I should have a better idea after that.

**Comment by jotak** [comment]
Anyway that's something I wanted to implement, so here it is #20

**Comment by jotak** [comment]
Can we close this issue or is there more enhancement to bring?
